### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by ghost**
Add French translation

### CODE REVIEW

**Comment by derjasper** [comment]
Thanks for the translations!
Please submit translations in future here: https://www.transifex.com/derjasper/tankenapp/
I already imported your translations there.

**Comment by ghost** [comment]
Thanks for your amazing work!
Have you ever considered to host the translations in [Launchpad](https://wiki.ubuntu.com/Translations/LpProjectConfiguration), this way the translation could be more easily reviewed by Ubuntu Translators?

**Comment by derjasper** [comment]
Yes, I thought about that. Transifex is not that good, so expect that I'll switch soon. ;)

**Comment by derjasper** [comment]
I migrated translations to launchpad ;)

**Comment by ghost** [comment]
Awsome!
Thanks a lot.

**Pull request merged**
